# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Accueil
    url: '#about'
    weight: 10
  - name: Parcours
    url: '#experience'
    weight: 20
  - name: Publications
    url: 'publication/'
    weight: 30
  - name: Projets
    url: '#projects'
    weight: 40
  - name: Blog
    url: '#posts'
    weight: 50
  - name: Pr√©sentations
    url: '#talks'
  - name: Enseignement
    url: 'content/cours/'
    weight: 40
# - name: Contact
#   url: '#contact'
#   weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
